export const MANIFESTO = [
  "WELCOME TO CRAZYROOM: WHERE DIGITAL WEIRDNESS MEETS MAXIMUM CHAOS",
  "NO RULES. NO LIMITS. PURE DIGITAL CRAZINESS.",
  "CRAZY STUFF PROCESSING AT MAXIMUM SPEED",
  "REALITY CHECKS PROCESSED AT MEME SPEED",
  "INFINITE WEIRD IDEAS, UNLIMITED FUN COMPUTED",
  "WHERE EVERY RESPONSE IS MADE WITH MAXIMUM WEIRDNESS"
];